#pragma once

#define CURRENT_VERSION "v1.2.13b"

#define UNLOAD_KEY VK_END
#define UNLOAD_KEY_ALT VK_DELETE
#define CONSOLE_KEY VK_HOME

#define TARGET_VERSION "936214"

#define NOMINMAX

#define ULOCALPLAYER_GETVIEWPOINT_INDEX 0x50
#define APLAYERCONTROLLER_GETPLAYERVIEWPOINT_INDEX 0xED

// To update SDK offsets 
/// @file ./Dumper-7/SDK/Basic.hpp:34