#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Mask_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function ABP_Mask_Base.ABP_Mask_Base_C.ExecuteUbergraph_ABP_Mask_Base
// 0x0004 (0x0004 - 0x0000)
struct ABP_Mask_Base_C_ExecuteUbergraph_ABP_Mask_Base
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function ABP_Mask_Base.ABP_Mask_Base_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ABP_Mask_Base_C_AnimGraph
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
