#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioExtensions

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class AudioExtensions.SoundfieldEncodingSettingsBase
// 0x0000 (0x0030 - 0x0030)
class USoundfieldEncodingSettingsBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundfieldEncodingSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundfieldEncodingSettingsBase")
	}
	static class USoundfieldEncodingSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundfieldEncodingSettingsBase>();
	}
};

// Class AudioExtensions.AudioEndpointSettingsBase
// 0x0000 (0x0030 - 0x0030)
class UAudioEndpointSettingsBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AudioEndpointSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AudioEndpointSettingsBase")
	}
	static class UAudioEndpointSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioEndpointSettingsBase>();
	}
};

// Class AudioExtensions.DummyEndpointSettings
// 0x0000 (0x0030 - 0x0030)
class UDummyEndpointSettings : public UAudioEndpointSettingsBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DummyEndpointSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DummyEndpointSettings")
	}
	static class UDummyEndpointSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDummyEndpointSettings>();
	}
};

// Class AudioExtensions.SpatializationPluginSourceSettingsBase
// 0x0000 (0x0030 - 0x0030)
class USpatializationPluginSourceSettingsBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SpatializationPluginSourceSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SpatializationPluginSourceSettingsBase")
	}
	static class USpatializationPluginSourceSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpatializationPluginSourceSettingsBase>();
	}
};

// Class AudioExtensions.OcclusionPluginSourceSettingsBase
// 0x0000 (0x0030 - 0x0030)
class UOcclusionPluginSourceSettingsBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OcclusionPluginSourceSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OcclusionPluginSourceSettingsBase")
	}
	static class UOcclusionPluginSourceSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOcclusionPluginSourceSettingsBase>();
	}
};

// Class AudioExtensions.ReverbPluginSourceSettingsBase
// 0x0000 (0x0030 - 0x0030)
class UReverbPluginSourceSettingsBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ReverbPluginSourceSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ReverbPluginSourceSettingsBase")
	}
	static class UReverbPluginSourceSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UReverbPluginSourceSettingsBase>();
	}
};

// Class AudioExtensions.SoundModulatorBase
// 0x0000 (0x0030 - 0x0030)
class USoundModulatorBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundModulatorBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundModulatorBase")
	}
	static class USoundModulatorBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundModulatorBase>();
	}
};

// Class AudioExtensions.SoundfieldEndpointSettingsBase
// 0x0000 (0x0030 - 0x0030)
class USoundfieldEndpointSettingsBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundfieldEndpointSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundfieldEndpointSettingsBase")
	}
	static class USoundfieldEndpointSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundfieldEndpointSettingsBase>();
	}
};

// Class AudioExtensions.SoundfieldEffectSettingsBase
// 0x0000 (0x0030 - 0x0030)
class USoundfieldEffectSettingsBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundfieldEffectSettingsBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundfieldEffectSettingsBase")
	}
	static class USoundfieldEffectSettingsBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundfieldEffectSettingsBase>();
	}
};

// Class AudioExtensions.SoundfieldEffectBase
// 0x0008 (0x0038 - 0x0030)
class USoundfieldEffectBase : public UObject
{
public:
	class USoundfieldEffectSettingsBase*          Settings;                                          // 0x0030(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SoundfieldEffectBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundfieldEffectBase")
	}
	static class USoundfieldEffectBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundfieldEffectBase>();
	}
};

SDK_NAMESPACE_END
