#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CarriedBlueKeycard

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CarriedBlueKeycard.BP_CarriedBlueKeycard_C.UserConstructionScript
// 0x0001 (0x0001 - 0x0000)
struct BP_CarriedBlueKeycard_C_UserConstructionScript
{
public:
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BP_CarriedBlueKeycard.BP_CarriedBlueKeycard_C.GetSensorOutlineComponent
// 0x0008 (0x0008 - 0x0000)
struct BP_CarriedBlueKeycard_C_GetSensorOutlineComponent
{
public:
	class USBZOutlineComponent*                   ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_CarriedBlueKeycard.BP_CarriedBlueKeycard_C.GetSensorComponent
// 0x0008 (0x0008 - 0x0000)
struct BP_CarriedBlueKeycard_C_GetSensorComponent
{
public:
	class USBZSensorComponent*                    ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

