#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RappellingRope

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RappellingRope.BP_RappellingRope_C
// 0x0000 (0x02D8 - 0x02D8)
class ABP_RappellingRope_C : public ASBZRappellingRope
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RappellingRope_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RappellingRope_C")
	}
	static class ABP_RappellingRope_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RappellingRope_C>();
	}
};

}

