#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_Villa_IntroOutro

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass C_Villa_IntroOutro.C_Villa_IntroOutro_C
// 0x0010 (0x0350 - 0x0340)
class AC_Villa_IntroOutro_C final : public ASBZLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ALevelSequenceActor*                    C_Villa_Master_2_ExecuteUbergraph_C_Villa_IntroOutro_RefProperty; // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnIntroFinished();
	void IntroSequenceChanged(bool bIsStarted);
	void ExecuteUbergraph_C_Villa_IntroOutro(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("C_Villa_IntroOutro_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"C_Villa_IntroOutro_C")
	}
	static class AC_Villa_IntroOutro_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AC_Villa_IntroOutro_C>();
	}
};
DUMPER7_ASSERTS_AC_Villa_IntroOutro_C;

}

