#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CinematicCamera

#include "Basic.hpp"

#include "CinematicCamera_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function CinematicCamera.CameraRig_Rail.GetRailSplineComponent
// 0x0008 (0x0008 - 0x0000)
struct CameraRig_Rail_GetRailSplineComponent
{
public:
	class USplineComponent*                       ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraActor.GetCineCameraComponent
// 0x0008 (0x0008 - 0x0000)
struct CineCameraActor_GetCineCameraComponent
{
public:
	class UCineCameraComponent*                   ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.GetFilmbackPresetsCopy
// 0x0010 (0x0010 - 0x0000)
struct CineCameraComponent_GetFilmbackPresetsCopy
{
public:
	TArray<struct FNamedFilmbackPreset>           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.GetLensPresetsCopy
// 0x0010 (0x0010 - 0x0000)
struct CineCameraComponent_GetLensPresetsCopy
{
public:
	TArray<struct FNamedLensPreset>               ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.SetCurrentFocalLength
// 0x0004 (0x0004 - 0x0000)
struct CineCameraComponent_SetCurrentFocalLength
{
public:
	float                                         InFocalLength;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.SetFilmbackPresetByName
// 0x0010 (0x0010 - 0x0000)
struct CineCameraComponent_SetFilmbackPresetByName
{
public:
	class FString                                 InPresetName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.SetLensPresetByName
// 0x0010 (0x0010 - 0x0000)
struct CineCameraComponent_SetLensPresetByName
{
public:
	class FString                                 InPresetName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.GetDefaultFilmbackPresetName
// 0x0010 (0x0010 - 0x0000)
struct CineCameraComponent_GetDefaultFilmbackPresetName
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.GetFilmbackPresetName
// 0x0010 (0x0010 - 0x0000)
struct CineCameraComponent_GetFilmbackPresetName
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.GetHorizontalFieldOfView
// 0x0004 (0x0004 - 0x0000)
struct CineCameraComponent_GetHorizontalFieldOfView
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.GetLensPresetName
// 0x0010 (0x0010 - 0x0000)
struct CineCameraComponent_GetLensPresetName
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CinematicCamera.CineCameraComponent.GetVerticalFieldOfView
// 0x0004 (0x0004 - 0x0000)
struct CineCameraComponent_GetVerticalFieldOfView
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
