#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DLSSBlueprint

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "DLSSBlueprint_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function DLSSBlueprint.DLSSLibrary.EnableDLAA
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_EnableDLAA
{
public:
	bool                                          bEnabled;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.EnableDLSS
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_EnableDLSS
{
public:
	bool                                          bEnabled;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.EnableDLSSRR
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_EnableDLSSRR
{
public:
	bool                                          bEnabled;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.GetDefaultDLSSMode
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_GetDefaultDLSSMode
{
public:
	EUDLSSMode                                    ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.GetDLSSMinimumDriverVersion
// 0x0008 (0x0008 - 0x0000)
struct DLSSLibrary_GetDLSSMinimumDriverVersion
{
public:
	int32                                         MinDriverVersionMajor;                             // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MinDriverVersionMinor;                             // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.GetDLSSMode
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_GetDLSSMode
{
public:
	EUDLSSMode                                    ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.GetDLSSModeInformation
// 0x0024 (0x0024 - 0x0000)
struct DLSSLibrary_GetDLSSModeInformation
{
public:
	EUDLSSMode                                    DLSSMode;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              ScreenResolution;                                  // 0x0004(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsSupported;                                      // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         OptimalScreenPercentage;                           // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsFixedScreenPercentage;                          // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MinScreenPercentage;                               // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxScreenPercentage;                               // 0x001C(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OptimalSharpness;                                  // 0x0020(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.GetDLSSRRMinimumDriverVersion
// 0x0008 (0x0008 - 0x0000)
struct DLSSLibrary_GetDLSSRRMinimumDriverVersion
{
public:
	int32                                         MinDriverVersionMajor;                             // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MinDriverVersionMinor;                             // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.GetDLSSScreenPercentageRange
// 0x0008 (0x0008 - 0x0000)
struct DLSSLibrary_GetDLSSScreenPercentageRange
{
public:
	float                                         MinScreenPercentage;                               // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxScreenPercentage;                               // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.GetDLSSSharpness
// 0x0004 (0x0004 - 0x0000)
struct DLSSLibrary_GetDLSSSharpness
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.GetSupportedDLSSModes
// 0x0010 (0x0010 - 0x0000)
struct DLSSLibrary_GetSupportedDLSSModes
{
public:
	TArray<EUDLSSMode>                            ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.IsDLAAEnabled
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_IsDLAAEnabled
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.IsDLSSEnabled
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_IsDLSSEnabled
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.IsDLSSModeSupported
// 0x0002 (0x0002 - 0x0000)
struct DLSSLibrary_IsDLSSModeSupported
{
public:
	EUDLSSMode                                    DLSSMode;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.IsDLSSRREnabled
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_IsDLSSRREnabled
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.IsDLSSRRSupported
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_IsDLSSRRSupported
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.IsDLSSSupported
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_IsDLSSSupported
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.QueryDLSSRRSupport
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_QueryDLSSRRSupport
{
public:
	EUDLSSSupport                                 ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.QueryDLSSSupport
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_QueryDLSSSupport
{
public:
	EUDLSSSupport                                 ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.SetDLSSMode
// 0x0001 (0x0001 - 0x0000)
struct DLSSLibrary_SetDLSSMode
{
public:
	EUDLSSMode                                    DLSSMode;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function DLSSBlueprint.DLSSLibrary.SetDLSSSharpness
// 0x0004 (0x0004 - 0x0000)
struct DLSSLibrary_SetDLSSSharpness
{
public:
	float                                         Sharpness;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
