#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HoudiniEngineRuntime

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function HoudiniEngineRuntime.HoudiniAssetBlueprintComponent.HasParameter
// 0x0018 (0x0018 - 0x0000)
struct HoudiniAssetBlueprintComponent_HasParameter
{
public:
	class FString                                 Name_0;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function HoudiniEngineRuntime.HoudiniAssetBlueprintComponent.SetFloatParameter
// 0x0018 (0x0018 - 0x0000)
struct HoudiniAssetBlueprintComponent_SetFloatParameter
{
public:
	class FString                                 Name_0;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Value;                                             // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Index_0;                                           // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniAssetBlueprintComponent.SetToggleValueAt
// 0x0018 (0x0018 - 0x0000)
struct HoudiniAssetBlueprintComponent_SetToggleValueAt
{
public:
	class FString                                 Name_0;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Value;                                             // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Index_0;                                           // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.AddStaticMaterial
// 0x0040 (0x0040 - 0x0000)
struct HoudiniStaticMesh_AddStaticMaterial
{
public:
	struct FStaticMaterial                        InStaticMaterial;                                  // 0x0000(0x0038)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	uint32                                        ReturnValue;                                       // 0x0038(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.CalculateNormals
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_CalculateNormals
{
public:
	bool                                          bInComputeWeightedNormals;                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.CalculateTangents
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_CalculateTangents
{
public:
	bool                                          bInComputeWeightedNormals;                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetMaterial
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetMaterial
{
public:
	int32                                         InMaterialIndex;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.Initialize
// 0x0014 (0x0014 - 0x0000)
struct HoudiniStaticMesh_Initialize
{
public:
	uint32                                        InNumVertices;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        InNumTriangles;                                    // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        InNumUVLayers;                                     // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        InInitialNumStaticMaterials;                       // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInHasNormals;                                     // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInHasTangents;                                    // 0x0011(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInHasColors;                                      // 0x0012(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInHasPerFaceMaterials;                            // 0x0013(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetHasColors
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_SetHasColors
{
public:
	bool                                          bInHasColors;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetHasNormals
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_SetHasNormals
{
public:
	bool                                          bInHasNormals;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetHasPerFaceMaterials
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_SetHasPerFaceMaterials
{
public:
	bool                                          bInHasPerFaceMaterials;                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetHasTangents
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_SetHasTangents
{
public:
	bool                                          bInHasTangents;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetNumStaticMaterials
// 0x0004 (0x0004 - 0x0000)
struct HoudiniStaticMesh_SetNumStaticMaterials
{
public:
	uint32                                        InNumStaticMaterials;                              // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetNumUVLayers
// 0x0004 (0x0004 - 0x0000)
struct HoudiniStaticMesh_SetNumUVLayers
{
public:
	uint32                                        InNumUVLayers;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetStaticMaterial
// 0x0040 (0x0040 - 0x0000)
struct HoudiniStaticMesh_SetStaticMaterial
{
public:
	uint32                                        InMaterialIndex;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStaticMaterial                        InStaticMaterial;                                  // 0x0008(0x0038)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetTriangleMaterialID
// 0x0008 (0x0008 - 0x0000)
struct HoudiniStaticMesh_SetTriangleMaterialID
{
public:
	uint32                                        InTriangleIndex;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InMaterialID;                                      // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetTriangleVertexColor
// 0x000C (0x000C - 0x0000)
struct HoudiniStaticMesh_SetTriangleVertexColor
{
public:
	uint32                                        InTriangleIndex;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         InTriangleVertexIndex;                             // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FColor                                 InColor;                                           // 0x0008(0x0004)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetTriangleVertexIndices
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_SetTriangleVertexIndices
{
public:
	uint32                                        InTriangleIndex;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FIntVector                             InTriangleVertexIndices;                           // 0x0004(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetTriangleVertexNormal
// 0x0014 (0x0014 - 0x0000)
struct HoudiniStaticMesh_SetTriangleVertexNormal
{
public:
	uint32                                        InTriangleIndex;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         InTriangleVertexIndex;                             // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                InNormal;                                          // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetTriangleVertexUTangent
// 0x0014 (0x0014 - 0x0000)
struct HoudiniStaticMesh_SetTriangleVertexUTangent
{
public:
	uint32                                        InTriangleIndex;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         InTriangleVertexIndex;                             // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                InUTangent;                                        // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetTriangleVertexUV
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_SetTriangleVertexUV
{
public:
	uint32                                        InTriangleIndex;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         InTriangleVertexIndex;                             // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         InUVLayer;                                         // 0x0005(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              InUV;                                              // 0x0008(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetTriangleVertexVTangent
// 0x0014 (0x0014 - 0x0000)
struct HoudiniStaticMesh_SetTriangleVertexVTangent
{
public:
	uint32                                        InTriangleIndex;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         InTriangleVertexIndex;                             // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                InVTangent;                                        // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.SetVertexPosition
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_SetVertexPosition
{
public:
	uint32                                        InVertexIndex;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                InPosition;                                        // 0x0004(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.CalcBounds
// 0x001C (0x001C - 0x0000)
struct HoudiniStaticMesh_CalcBounds
{
public:
	struct FBox                                   ReturnValue;                                       // 0x0000(0x001C)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetMaterialIDsPerTriangle
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetMaterialIDsPerTriangle
{
public:
	TArray<int32>                                 ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetMaterialIndex
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetMaterialIndex
{
public:
	class FName                                   InMaterialSlotName;                                // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x000C(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetNumStaticMaterials
// 0x0004 (0x0004 - 0x0000)
struct HoudiniStaticMesh_GetNumStaticMaterials
{
public:
	uint32                                        ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetNumTriangles
// 0x0004 (0x0004 - 0x0000)
struct HoudiniStaticMesh_GetNumTriangles
{
public:
	uint32                                        ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetNumUVLayers
// 0x0004 (0x0004 - 0x0000)
struct HoudiniStaticMesh_GetNumUVLayers
{
public:
	uint32                                        ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetNumVertexInstances
// 0x0004 (0x0004 - 0x0000)
struct HoudiniStaticMesh_GetNumVertexInstances
{
public:
	uint32                                        ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetNumVertices
// 0x0004 (0x0004 - 0x0000)
struct HoudiniStaticMesh_GetNumVertices
{
public:
	uint32                                        ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetStaticMaterials
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetStaticMaterials
{
public:
	TArray<struct FStaticMaterial>                ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetTriangleIndices
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetTriangleIndices
{
public:
	TArray<struct FIntVector>                     ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetVertexInstanceColors
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetVertexInstanceColors
{
public:
	TArray<struct FColor>                         ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetVertexInstanceNormals
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetVertexInstanceNormals
{
public:
	TArray<struct FVector>                        ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetVertexInstanceUTangents
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetVertexInstanceUTangents
{
public:
	TArray<struct FVector>                        ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetVertexInstanceUVs
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetVertexInstanceUVs
{
public:
	TArray<struct FVector2D>                      ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetVertexInstanceVTangents
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetVertexInstanceVTangents
{
public:
	TArray<struct FVector>                        ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.GetVertexPositions
// 0x0010 (0x0010 - 0x0000)
struct HoudiniStaticMesh_GetVertexPositions
{
public:
	TArray<struct FVector>                        ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.HasColors
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_HasColors
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.HasNormals
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_HasNormals
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.HasPerFaceMaterials
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_HasPerFaceMaterials
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.HasTangents
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMesh_HasTangents
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMesh.IsValid
// 0x0002 (0x0002 - 0x0000)
struct HoudiniStaticMesh_IsValid
{
public:
	bool                                          bInSkipVertexIndicesCheck;                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMeshComponent.GetMesh
// 0x0008 (0x0008 - 0x0000)
struct HoudiniStaticMeshComponent_GetMesh
{
public:
	class UHoudiniStaticMesh*                     ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMeshComponent.SetHoudiniIconVisible
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMeshComponent_SetHoudiniIconVisible
{
public:
	bool                                          bInHoudiniIconVisible;                             // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMeshComponent.SetMesh
// 0x0008 (0x0008 - 0x0000)
struct HoudiniStaticMeshComponent_SetMesh
{
public:
	class UHoudiniStaticMesh*                     InMesh;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function HoudiniEngineRuntime.HoudiniStaticMeshComponent.IsHoudiniIconVisible
// 0x0001 (0x0001 - 0x0000)
struct HoudiniStaticMeshComponent_IsHoudiniIconVisible
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
