#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LiveLink

#include "Basic.hpp"

#include "LiveLinkInterface_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "LiveLink_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function LiveLink.LiveLinkBlueprintLibrary.ChildCount
// 0x0028 (0x0028 - 0x0000)
struct LiveLinkBlueprintLibrary_ChildCount
{
public:
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0000(0x0020)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0020(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.ComponentSpaceTransform
// 0x0050 (0x0050 - 0x0000)
struct LiveLinkBlueprintLibrary_ComponentSpaceTransform
{
public:
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0000(0x0020)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FTransform                             Transform;                                         // 0x0020(0x0030)(Parm, OutParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.EvaluateLiveLinkFrame
// 0x0028 (0x0028 - 0x0000)
struct LiveLinkBlueprintLibrary_EvaluateLiveLinkFrame
{
public:
	struct FLiveLinkSubjectRepresentation         SubjectRepresentation;                             // 0x0000(0x0018)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	struct FLiveLinkBaseBlueprintData             OutBlueprintData;                                  // 0x0018(0x0008)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.EvaluateLiveLinkFrameAtSceneTime
// 0x0040 (0x0040 - 0x0000)
struct LiveLinkBlueprintLibrary_EvaluateLiveLinkFrameAtSceneTime
{
public:
	struct FLiveLinkSubjectName                   SubjectName;                                       // 0x0000(0x000C)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class ULiveLinkRole>              Role;                                              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FTimecode                              SceneTime;                                         // 0x0018(0x0014)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLiveLinkBaseBlueprintData             OutBlueprintData;                                  // 0x0030(0x0008)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0038(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.EvaluateLiveLinkFrameAtWorldTimeOffset
// 0x0030 (0x0030 - 0x0000)
struct LiveLinkBlueprintLibrary_EvaluateLiveLinkFrameAtWorldTimeOffset
{
public:
	struct FLiveLinkSubjectName                   SubjectName;                                       // 0x0000(0x000C)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class ULiveLinkRole>              Role;                                              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WorldTimeOffset;                                   // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLiveLinkBaseBlueprintData             OutBlueprintData;                                  // 0x0020(0x0008)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0028(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.EvaluateLiveLinkFrameWithSpecificRole
// 0x0028 (0x0028 - 0x0000)
struct LiveLinkBlueprintLibrary_EvaluateLiveLinkFrameWithSpecificRole
{
public:
	struct FLiveLinkSubjectName                   SubjectName;                                       // 0x0000(0x000C)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class ULiveLinkRole>              Role;                                              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLiveLinkBaseBlueprintData             OutBlueprintData;                                  // 0x0018(0x0008)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetAnimationFrameData
// 0x00D0 (0x00D0 - 0x0000)
struct LiveLinkBlueprintLibrary_GetAnimationFrameData
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FLiveLinkAnimationFrameData            AnimationFrameData;                                // 0x0018(0x00B0)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x00C8(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetAnimationStaticData
// 0x0050 (0x0050 - 0x0000)
struct LiveLinkBlueprintLibrary_GetAnimationStaticData
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FLiveLinkSkeletonStaticData            AnimationStaticData;                               // 0x0018(0x0030)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0048(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetBasicData
// 0x00D0 (0x00D0 - 0x0000)
struct LiveLinkBlueprintLibrary_GetBasicData
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FLiveLinkBasicBlueprintData            BasicBlueprintData;                                // 0x0018(0x00B8)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetChildren
// 0x0030 (0x0030 - 0x0000)
struct LiveLinkBlueprintLibrary_GetChildren
{
public:
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0000(0x0020)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TArray<struct FLiveLinkTransform>             Children;                                          // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetCurves
// 0x0068 (0x0068 - 0x0000)
struct LiveLinkBlueprintLibrary_GetCurves
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TMap<class FName, float>                      Curves;                                            // 0x0018(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetLiveLinkEnabledSubjectNames
// 0x0018 (0x0018 - 0x0000)
struct LiveLinkBlueprintLibrary_GetLiveLinkEnabledSubjectNames
{
public:
	bool                                          bIncludeVirtualSubject;                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FLiveLinkSubjectName>           ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetLiveLinkSubjectRole
// 0x0018 (0x0018 - 0x0000)
struct LiveLinkBlueprintLibrary_GetLiveLinkSubjectRole
{
public:
	struct FLiveLinkSubjectName                   SubjectName;                                       // 0x0000(0x000C)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class ULiveLinkRole>              ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetLiveLinkSubjects
// 0x0018 (0x0018 - 0x0000)
struct LiveLinkBlueprintLibrary_GetLiveLinkSubjects
{
public:
	bool                                          bIncludeDisabledSubject;                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIncludeVirtualSubject;                            // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FLiveLinkSubjectKey>            ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetMetadata
// 0x0088 (0x0088 - 0x0000)
struct LiveLinkBlueprintLibrary_GetMetadata
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FSubjectMetadata                       Metadata;                                          // 0x0018(0x0070)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetParent
// 0x0040 (0x0040 - 0x0000)
struct LiveLinkBlueprintLibrary_GetParent
{
public:
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0000(0x0020)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FLiveLinkTransform                     Parent;                                            // 0x0020(0x0020)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetPropertyValue
// 0x00D0 (0x00D0 - 0x0000)
struct LiveLinkBlueprintLibrary_GetPropertyValue
{
public:
	struct FLiveLinkBasicBlueprintData            BasicData;                                         // 0x0000(0x00B8)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FName                                   PropertyName;                                      // 0x00B8(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Value;                                             // 0x00C4(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x00C8(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetRootTransform
// 0x0038 (0x0038 - 0x0000)
struct LiveLinkBlueprintLibrary_GetRootTransform
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0018(0x0020)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetSourceMachineName
// 0x0030 (0x0030 - 0x0000)
struct LiveLinkBlueprintLibrary_GetSourceMachineName
{
public:
	struct FLiveLinkSourceHandle                  SourceHandle;                                      // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FText                                   ReturnValue;                                       // 0x0018(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetSourceStatus
// 0x0030 (0x0030 - 0x0000)
struct LiveLinkBlueprintLibrary_GetSourceStatus
{
public:
	struct FLiveLinkSourceHandle                  SourceHandle;                                      // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FText                                   ReturnValue;                                       // 0x0018(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetSourceType
// 0x0030 (0x0030 - 0x0000)
struct LiveLinkBlueprintLibrary_GetSourceType
{
public:
	struct FLiveLinkSourceHandle                  SourceHandle;                                      // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FText                                   ReturnValue;                                       // 0x0018(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetSpecificLiveLinkSubjectRole
// 0x0028 (0x0028 - 0x0000)
struct LiveLinkBlueprintLibrary_GetSpecificLiveLinkSubjectRole
{
public:
	struct FLiveLinkSubjectKey                    SubjectKey;                                        // 0x0000(0x001C)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class ULiveLinkRole>              ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetTransformByIndex
// 0x0040 (0x0040 - 0x0000)
struct LiveLinkBlueprintLibrary_GetTransformByIndex
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         TransformIndex;                                    // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0020(0x0020)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.GetTransformByName
// 0x0048 (0x0048 - 0x0000)
struct LiveLinkBlueprintLibrary_GetTransformByName
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FName                                   TransformName_0;                                   // 0x0018(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0028(0x0020)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.HasParent
// 0x0028 (0x0028 - 0x0000)
struct LiveLinkBlueprintLibrary_HasParent
{
public:
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0000(0x0020)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.IsLiveLinkSubjectEnabled
// 0x0010 (0x0010 - 0x0000)
struct LiveLinkBlueprintLibrary_IsLiveLinkSubjectEnabled
{
public:
	struct FLiveLinkSubjectName                   SubjectName;                                       // 0x0000(0x000C)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.IsSourceStillValid
// 0x0020 (0x0020 - 0x0000)
struct LiveLinkBlueprintLibrary_IsSourceStillValid
{
public:
	struct FLiveLinkSourceHandle                  SourceHandle;                                      // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.IsSpecificLiveLinkSubjectEnabled
// 0x0020 (0x0020 - 0x0000)
struct LiveLinkBlueprintLibrary_IsSpecificLiveLinkSubjectEnabled
{
public:
	struct FLiveLinkSubjectKey                    SubjectKey;                                        // 0x0000(0x001C)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForThisFrame;                                     // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x001D(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.NumberOfTransforms
// 0x0020 (0x0020 - 0x0000)
struct LiveLinkBlueprintLibrary_NumberOfTransforms
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.ParentBoneSpaceTransform
// 0x0050 (0x0050 - 0x0000)
struct LiveLinkBlueprintLibrary_ParentBoneSpaceTransform
{
public:
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0000(0x0020)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FTransform                             Transform;                                         // 0x0020(0x0030)(Parm, OutParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintLibrary.RemoveSource
// 0x0020 (0x0020 - 0x0000)
struct LiveLinkBlueprintLibrary_RemoveSource
{
public:
	struct FLiveLinkSourceHandle                  SourceHandle;                                      // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.SetLiveLinkSubjectEnabled
// 0x0020 (0x0020 - 0x0000)
struct LiveLinkBlueprintLibrary_SetLiveLinkSubjectEnabled
{
public:
	struct FLiveLinkSubjectKey                    SubjectKey;                                        // 0x0000(0x001C)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnabled;                                          // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.TransformName
// 0x0030 (0x0030 - 0x0000)
struct LiveLinkBlueprintLibrary_TransformName
{
public:
	struct FLiveLinkTransform                     LiveLinkTransform;                                 // 0x0000(0x0020)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FName                                   Name_0;                                            // 0x0020(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintLibrary.TransformNames
// 0x0028 (0x0028 - 0x0000)
struct LiveLinkBlueprintLibrary_TransformNames
{
public:
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TArray<class FName>                           TransformNames_0;                                  // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkBlueprintVirtualSubject.UpdateVirtualSubjectFrameData_Internal
// 0x00A8 (0x00A8 - 0x0000)
struct LiveLinkBlueprintVirtualSubject_UpdateVirtualSubjectFrameData_Internal
{
public:
	struct FLiveLinkBaseFrameData                 InStruct;                                          // 0x0000(0x00A0)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          bInShouldStampCurrentTime;                         // 0x00A0(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x00A1(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A2[0x6];                                       // 0x00A2(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkBlueprintVirtualSubject.UpdateVirtualSubjectStaticData_Internal
// 0x0018 (0x0018 - 0x0000)
struct LiveLinkBlueprintVirtualSubject_UpdateVirtualSubjectStaticData_Internal
{
public:
	struct FLiveLinkBaseStaticData                InStruct;                                          // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function LiveLink.LiveLinkComponent.GetAvailableSubjectNames
// 0x0010 (0x0010 - 0x0000)
struct LiveLinkComponent_GetAvailableSubjectNames
{
public:
	TArray<class FName>                           SubjectNames;                                      // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkComponent.GetSubjectData
// 0x0028 (0x0028 - 0x0000)
struct LiveLinkComponent_GetSubjectData
{
public:
	class FName                                   SubjectName;                                       // 0x0000(0x000C)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSuccess;                                          // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0010(0x0018)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkComponent.GetSubjectDataAtSceneTime
// 0x0040 (0x0040 - 0x0000)
struct LiveLinkComponent_GetSubjectDataAtSceneTime
{
public:
	class FName                                   SubjectName;                                       // 0x0000(0x000C)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FTimecode                              SceneTime;                                         // 0x000C(0x0014)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSuccess;                                          // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0028(0x0018)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkComponent.GetSubjectDataAtWorldTime
// 0x0030 (0x0030 - 0x0000)
struct LiveLinkComponent_GetSubjectDataAtWorldTime
{
public:
	class FName                                   SubjectName;                                       // 0x0000(0x000C)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WorldTime;                                         // 0x000C(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSuccess;                                          // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSubjectFrameHandle                    SubjectFrameHandle;                                // 0x0018(0x0018)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkInstance.SetRetargetAsset
// 0x0008 (0x0008 - 0x0000)
struct LiveLinkInstance_SetRetargetAsset
{
public:
	TSubclassOf<class ULiveLinkRetargetAsset>     RetargetAsset;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkInstance.SetSubject
// 0x000C (0x000C - 0x0000)
struct LiveLinkInstance_SetSubject
{
public:
	struct FLiveLinkSubjectName                   SubjectName;                                       // 0x0000(0x000C)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkMessageBusFinder.ConnectToProvider
// 0x0050 (0x0050 - 0x0000)
struct LiveLinkMessageBusFinder_ConnectToProvider
{
public:
	struct FProviderPollResult                    Provider;                                          // 0x0000(0x0038)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FLiveLinkSourceHandle                  SourceHandle;                                      // 0x0038(0x0018)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkMessageBusFinder.ConstructMessageBusFinder
// 0x0008 (0x0008 - 0x0000)
struct LiveLinkMessageBusFinder_ConstructMessageBusFinder
{
public:
	class ULiveLinkMessageBusFinder*              ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkMessageBusFinder.GetAvailableProviders
// 0x0040 (0x0040 - 0x0000)
struct LiveLinkMessageBusFinder_GetAvailableProviders
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLatentActionInfo                      LatentInfo;                                        // 0x0008(0x0020)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	float                                         Duration;                                          // 0x0028(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FProviderPollResult>            AvailableProviders;                                // 0x0030(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkPreset.AddToClient
// 0x0002 (0x0002 - 0x0000)
struct LiveLinkPreset_AddToClient
{
public:
	bool                                          bRecreatePresets;                                  // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkPreset.ApplyToClient
// 0x0001 (0x0001 - 0x0000)
struct LiveLinkPreset_ApplyToClient
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkRemapAsset.GetRemappedBoneName
// 0x0018 (0x0018 - 0x0000)
struct LiveLinkRemapAsset_GetRemappedBoneName
{
public:
	class FName                                   BoneName;                                          // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ReturnValue;                                       // 0x000C(0x000C)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkRemapAsset.GetRemappedCurveName
// 0x0018 (0x0018 - 0x0000)
struct LiveLinkRemapAsset_GetRemappedCurveName
{
public:
	class FName                                   CurveName;                                         // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ReturnValue;                                       // 0x000C(0x000C)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function LiveLink.LiveLinkRemapAsset.RemapCurveElements
// 0x0050 (0x0050 - 0x0000)
struct LiveLinkRemapAsset_RemapCurveElements
{
public:
	TMap<class FName, float>                      CurveItems;                                        // 0x0000(0x0050)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
