#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UTS_Commit

#include "Basic.hpp"

#include "AIModule_structs.hpp"


namespace SDK::Params
{

// Function UTS_Commit.UTS_Commit_C.ExecuteUbergraph_UTS_Commit
// 0x0008 (0x0008 - 0x0000)
struct UTS_Commit_C_ExecuteUbergraph_UTS_Commit
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBTNodeResult                                 K2Node_Event_NodeResult;                           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UTS_Commit.UTS_Commit_C.OnDeactivatedBP
// 0x0001 (0x0001 - 0x0000)
struct UTS_Commit_C_OnDeactivatedBP
{
public:
	EBTNodeResult                                 NodeResult;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UTS_Commit.UTS_Commit_C.CalcScoreBP
// 0x0004 (0x0004 - 0x0000)
struct UTS_Commit_C_CalcScoreBP
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

