#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Villa

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Villa.Villa_C
// 0x0000 (0x0340 - 0x0340)
class AVilla_C : public ASBZLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Villa_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Villa_C")
	}
	static class AVilla_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVilla_C>();
	}
};

}

