#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Loadout_ConfirmationPopup

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_Loadout_ConfirmationPopup.WBP_Loadout_ConfirmationPopup_C.ExecuteUbergraph_WBP_Loadout_ConfirmationPopup
// 0x0004 (0x0004 - 0x0000)
struct WBP_Loadout_ConfirmationPopup_C_ExecuteUbergraph_WBP_Loadout_ConfirmationPopup
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
