#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_Debug_MainMenuVersionText_

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_UI_Widget_Debug_MainMenuVersionText_.WBP_UI_Widget_Debug_MainMenuVersionText__C.ExecuteUbergraph_WBP_UI_Widget_Debug_MainMenuVersionText_
// 0x0020 (0x0020 - 0x0000)
struct WBP_UI_Widget_Debug_MainMenuVersionText__C_ExecuteUbergraph_WBP_UI_Widget_Debug_MainMenuVersionText_
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0008(0x0018)()
};

// Function WBP_UI_Widget_Debug_MainMenuVersionText_.WBP_UI_Widget_Debug_MainMenuVersionText__C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_Widget_Debug_MainMenuVersionText__C_PreConstruct
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function WBP_UI_Widget_Debug_MainMenuVersionText_.WBP_UI_Widget_Debug_MainMenuVersionText__C.SetText
// 0x0028 (0x0028 - 0x0000)
struct WBP_UI_Widget_Debug_MainMenuVersionText__C_SetText
{
public:
	class FString                                 NewParam;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0010(0x0018)()
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
