#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CableBox

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_CableBox.WBP_CableBox_C.SetCodeText
// 0x0018 (0x0018 - 0x0000)
struct WBP_CableBox_C_SetCodeText
{
public:
	class FText                                   InText;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

// Function WBP_CableBox.WBP_CableBox_C.SetState
// 0x0018 (0x0018 - 0x0000)
struct WBP_CableBox_C_SetState
{
public:
	class FText                                   InText;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

}

