#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ComputerBase

#include "Basic.hpp"

#include "Starbreeze_structs.hpp"


namespace SDK::Params
{

// Function WBP_ComputerBase.WBP_ComputerBase_C.ExecuteUbergraph_WBP_ComputerBase
// 0x0158 (0x0158 - 0x0000)
struct WBP_ComputerBase_C_ExecuteUbergraph_WBP_ComputerBase
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_main;                           // 0x0008(0x0018)()
	class FText                                   K2Node_CustomEvent_secondary;                      // 0x0020(0x0018)(ConstParm)
	class FText                                   K2Node_CustomEvent_additional;                     // 0x0038(0x0018)()
	struct FSBZHackableDisplayText                K2Node_CustomEvent_NewDisplayText;                 // 0x0050(0x0060)()
	struct FSBZHackableDisplayText                K2Node_CustomEvent_DisplayText;                    // 0x00B0(0x0060)()
	class FText                                   K2Node_CustomEvent_InText_1;                       // 0x0110(0x0018)()
	class FText                                   K2Node_CustomEvent_InText;                         // 0x0128(0x0018)()
	int32                                         K2Node_CustomEvent_progress;                       // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_144[0x4];                                      // 0x0144(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 K2Node_CustomEvent_codes;                          // 0x0148(0x0010)(ConstParm, ReferenceParm)
};

// Function WBP_ComputerBase.WBP_ComputerBase_C.updateInformation
// 0x0048 (0x0048 - 0x0000)
struct WBP_ComputerBase_C_updateInformation
{
public:
	class FText                                   main;                                              // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   secondary;                                         // 0x0018(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   additional;                                        // 0x0030(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

// Function WBP_ComputerBase.WBP_ComputerBase_C.updateKeypadPossibleCodes
// 0x0010 (0x0010 - 0x0000)
struct WBP_ComputerBase_C_updateKeypadPossibleCodes
{
public:
	TArray<int32>                                 codes;                                             // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

// Function WBP_ComputerBase.WBP_ComputerBase_C.updateHackingProgress
// 0x0004 (0x0004 - 0x0000)
struct WBP_ComputerBase_C_updateHackingProgress
{
public:
	int32                                         progress;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_ComputerBase.WBP_ComputerBase_C.updateHackingTimerProcessName
// 0x0018 (0x0018 - 0x0000)
struct WBP_ComputerBase_C_updateHackingTimerProcessName
{
public:
	class FText                                   InText;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

// Function WBP_ComputerBase.WBP_ComputerBase_C.UpdateSuccessText
// 0x0018 (0x0018 - 0x0000)
struct WBP_ComputerBase_C_UpdateSuccessText
{
public:
	class FText                                   InText;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

// Function WBP_ComputerBase.WBP_ComputerBase_C.UpdateEmailDisplayText
// 0x0060 (0x0060 - 0x0000)
struct WBP_ComputerBase_C_UpdateEmailDisplayText
{
public:
	struct FSBZHackableDisplayText                DisplayText;                                       // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm)
};

// Function WBP_ComputerBase.WBP_ComputerBase_C.UpdateUnlockDisplayText
// 0x0060 (0x0060 - 0x0000)
struct WBP_ComputerBase_C_UpdateUnlockDisplayText
{
public:
	struct FSBZHackableDisplayText                NewDisplayText;                                    // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm)
};

}

